
# Introduction: Computational psycholingistic approaches applied to understanding convention formation in iterated reference games
 
## Motivations and definitions
One of the possibilities for human uniqueness is language. Language allows for the communication of many things. It allows for coordination between individuals, it  allows for gossip, it allows for the communication of complex and abstract ideas which allows for the cultural accumulation of technologies beyond what any one mind could come up with. Especially with the technological innovation of writing, it allows for communication across long distances of space and time. 

There are other modalities of communication used by humans and other species, but the structure of language gives it more expressivity than other systems. We learn native languages in the early years of life and this gives a shared set of symbol meaning mappings and combinatorial rules that can be used to communicate. Language is a very powerful system for transmitting ideas from mind to mind. Language is ubiquitous to (at least my) daily life, but it also feels like the more one considers langauge, the more there is to explain and the more impressive our linguistic capabilities seem.  

The word "language" can refer to a suite of related concepts, all of which can be the targets of study.    There's the abstract idea of a specific language, for instance, English as a set of grammatical rules and word meanings. But this breaks down on the edges -- it's an idealized abstraction. From a different formalism, we can view language as a particular communication channel, with high capacity compared to other channels.  From a more statistical perspective, there's also language as it is used by a certain community, not a static entity but something that evolves slowly over time. This too is a bit of an idealized abstraction as the grammars in the mind of individuals don't exactly align with each other, so the meaning is probabilistic or distributional. But even this individual abstraction is built out of individual exposures to language that unfold over time and some neural architecture that is producing and processing the language. There's the artifact of language -- corpuses of writings or utterances. There's language as a capacity for learning a system for expressing ideas and being able to express and understand ideas in a system. Language is also a tool that we use to communicate with each other, possibly twisting or bending constructions and meanings to accomplish communicative goals. Language is also a social thing for interacting with other humans. 

These different levels of meaning of the word language both make it a fascinating thing to study, but also lead to disagreements around what is studied in linguistics or the "language sciences". Here I will tend to focus on language as a tool for communication, but artifacts of language, language as a shared set of expectations, and language as a thing the mind processes are also lenses that will occur. 

In studying language use, what counts as language? Some might want to focus only on conversational face to face language use for communicative purposes, and exclude derivatives like wordplay or phonetic codes or language models as things that use the artifacts of language and some of their properties but maybe aren't language. However, beyond the focus on language as a particularly interesting communication modality, I do not assign primacy to any particular parts of language. We may find that some types of language use are easier to process than others, or that some uses require inferences that may not be language specific, but I will not assume a priori that certain parts of language are more privileged or central than others.  

Though not to the extent of the word language, the word "pragmatics" also means different things to different people, so I will clarify here that I mean pragmatics expansively as something along the lines of meaning in context or context as a component to inferring meaning (CITE). 

I start by pointing out that there's this terminology issue because I think it's important to scope the topic. This dissertation will focus on how we use language to communicate around the edges of expressivity -- how we extend our lexica to accomodate communicative needs that are on the border and how we are able to coordinate with each other in these ways. These linguistic stretches can be ad hoc and temporary, but these individual atypical usages are also what can spread and build up into the adoption of new words and meanings and language change. 

Why care about this? I think questions around language use *in context* are in a middle spot between being able to think about them in terms of theories and models of psycholinguistics, but that they are exploring interesting behaviors that have analogues that occur in real life. Broadly, context contributes to messiness (it's another thing to consider), but language use is usually deeply embedded in context. What do we do about the context is an interesting question both at more fine-grained levels of language specific processing and at more general levels of language as a communication tool. [TODO unclear what different folks consider a compelling answer to the "why study this answer"]

In the rest of the introduction, I will explain the motivation for using iterated reference games as a model system. I will then cover three main approaches from psycholinguistics that I believe may have useful applications to issues of iterated reference games: efficience, Bayesian pragmatics, and information theory. Then I will review findings and theories related to the conversational literature and think about whether these findings could be subsumed under the larger psycholinguistic frameworks. Finally, I will suggest what I see as some gaps in the literature and close with a preview of a few gaps in particular that I will address in the later chapters of this dissertation. 


## Why iterated reference games

Having covered in the first section some of what I think makes language an interesting domain to study, I now introduce the paradigm that will serve as a focus. 

Here we will focus on a particular paradigm for studying adaptive language use: the iterated reference game. A reference game consist of a set of people communicating with each other about a set of potential referents (often images). One person, the describer, has a specific designated target (usually pre-identified as the target by the experimentor) that they seek to communicate to the matcher (or matchers). This act of reference requires coordination between describer and matcher on a symbol -- meaning alignment. Iterated reference games involve repeated reference to the same targets within the same group of people, so that a certain conversational history builds up that could shape the construction and understanding of later symbols.  Crucially, this task uses referents that are somehow non-trivial to identify, usually by some combination of low-codeability or high-similarity to each other. 

As described, this task is agnostic to communication modality, and iterated reference games can be done using gestures or drawing [TODO citations]. However, I am interested in how this task interacts with the rich baseline of symbol -- meaning mappings afforded by natural language. Language is a communication system with a particularly rich set of shared baseline meanings and there is also a particularly rich of set knowledge regarding the study of language. However, I beleive that some of what we learn about language also transfers to other modalities of communication and vice versa. 

Why this task? 
When trying to study a complex system like language (or communication), there's a trade-off between how much one tries to encompass and how intractable it is to study. Paradigms are model systems, we want some aspects of them to parallel the messy real world but we also accept some aspects of unrealism that give us some explanatory control. 

One observation from real-life language use is that people use words in creative ways to express meanings sometimes. For instance, even if I don't know the name for something (or if it is known but evading memory as in tip-of-the-tongue events), I can still communicate about it in a more circuitous manner. And given the right communicative needs, this can conventionalize into a more settled expression to refer to a particular thing. 

Communicative acts serve a variety of purposes, but a simple, yet central one is reference: connecting a symbol with a meaning to pick out a target. This is a subgoal needed for more complex acts -- it's hard to tell a story or debate someone without agreement on what different words or phrases refer to. While language is used for many communicative acts, a core component is reference -- reaching agreement on the target that goes with a portion of linguistic material. What do those words index? Sometimes this can be isolated, as in reference games, but it is also a pre-requisite for various other communicative acts. It's hard to negotiate or coordinate when one doesn't agree on the targets of the NPs. 

Combining these observations -- that language can be adapted to fill communicative needs, that repeated need leads to changes in referring form, and that reference is a easy to elicit communicative act that is still important -- suggests the utility of iterated reference games. This is an ahistorical account -- but I suspect that considerations like these -- of striking the right balance between simiplicity, naturalness, and interesting elicited behavior -- are some of the motivations behind the use of iterated reference games in the literature. 

This task is commonly used. The earliest studies using it that I'm aware of are  from the 1960s TODO CITE KRAUSS, and it seems to have become more widely used in the 1980s. Over time it has been used in a wide variety of populations to study a wide variety of communicative and linguistic phenomena. Reasons people use iter ref games:

Iterated reference games have been used to study a number of issues. The primary targets of study are coordination and the formation of conventions or conceptual pacts [@dahan2025; @ghaleb2024; @eliav; @hawkins2020; @metzing; @brennan1996, among others]. Some studies focus particularly on iterated reference games as a way of studying collaboration in natural conversations [@dahan2024; @wilkes-gibbs1992; @schober1989; @clark1986]. Different studies focus on different aspects of the coordination, including the negotiation of referring expressions [@knutsenbigot; @bangerter2020] or the role of feedback [@krauss1966; @krauss1977;@foxtree2013]. These same types of games are used to study how speakers tailor to listeners with studies of audience design [@turner; @yoon2019; @yoonotherdates; @horton2004; @horton2002] and how speakers might generalize patterns of social conventions across interlocuters [@hawkinsrespectthecode; @hawkinsgeneralizingmeanings]. Iterated reference games are used as the dialogue condition in studies on the differences between monologue and dialogue [@tolins2017;@branigan2011;@murfitt; @foxtree1999]. There are also studies using this paradigm to model cultural conflicts between merging teams [@weber], look at speech-gesture tradeoffs [@deruiter], and study the effects of alcohol on social dynamics [@garrison].

In addition to studies on typical populations, iterated reference games are also used to study the abilities of special populations. Iterated reference games are used with children and teenagers [@leung2024; @branigan2016; @turner] and with other adults  [@lysander;@hortonspieler;@hupet1993] to study cognitive and linguistic abilites across the lifespan. Iterated reference games are used to study conversation and memory, in people with amesia  [@yoon2017;@duffteasing; @dufftheuseof; @duffdevelopment], and those without [@mckinley2017;  @vanlangendonck]. Iterated reference games have also been used to study perspective taking and theory of mind in patients with vmPFC damge [@gupta], theory of mind in people with schitzophrenia[@champagne-lavau], collaboration in people with aphasia [hengst], and conversational impairments in people with right-hemisphere brain damage [@chantraine1998].


## Frameworks

One question is whether the phenomena related to convention formation and iterated reference games are best thought of as an isolated, special occurrence or whether the results can be subsumed within a more general and broader coverage theory of language use. I review two general frameworks: efficiency and bayesian pragmatics. 

### Efficiency

One unifying framework gaining traction in psycholinguistics is efficiency, the idea that language and language use is under pressure to support efficient communication by maximizing the ratio of relevant information transmitted to effort. Efficiency is a high level framework that can only be tested against data when it is fleshed out with linking assumptions; hwoever, comparisons between language use that is attested versus counterfactual languages can bound what types of assumptions are needed for this framework to be parimonious. 

Efficiency is thought to arise from trade-offs between communicative expressivity and some combination of learnability and easy of production [@piantadosi2012; @kirby2015]. The state of language is thus in a dynamic equilibrium between the usage pressure to be able to communicate many ideas (pushing complexity of language) and some constraints pushing for simplicity of language, which could be either the requirement that languages be learnable or pressures for ease of production.

Evidence for efficiency comes from the argument that features of language are distributed much more closely to the Pareto frontier than would be expected by chance. A historically well-known example is that word frequencies follow a power-law distribution, which @zipf1949 explains in terms of a "principle of least effort", where words that are more frequent are also shorter. It is worth noting that this type of power-law distribution is common across domains and generated by a variety of processes, so while well known, it is not the strongest evidence for efficiency as a shaping factor [@piantadosi2014]. Stronger evidence comes from the lexical partitioning of subdomains such as color, number, and kinship terms, where the distribution of systems falls on the Pareto frontier between complexity (number of terms) and informativity (how many bits each term provides) [@zaslavsky2018;@kemp2018;@gibson2019]. Syntactic features of language such as harmonic word order and dependency length also appear to be optimized for increased expressivity with minimized processing effort [@gibson2019;@hawkins1995]. 
	
Efficiency arguments are based on the language artifacts of grammars and transcripts, but efficiency pressures act on language use as a process, not language as a static code [@gibson2019]. Thus efficiency can be seen as imposing a joint constraint on the entire communicative process: minimizing the total time and effort involved in going from an idea in one person's head to a sufficiently close idea in another person's head. A corollary of this framing is that while shorter utterances are usually considered more efficient, utterance length in syllables or clock-time is not actually what is under pressure, they would not be efficient if they took longer to produce or parse than alternatives.

As with other high level frameworks, the parsimony of the efficiency framework is entirely based on its auxiliary linking theories [@gershman2019]. Thus, the question becomes what sort of auxiliary assumptions are needed to connect a given phenomena under the efficiency umbrella, and how reasonable are those assumptions. 

As an illustration, I look at the issues of ambiguity and redundancy in referring expressions. 

#### Redundancy and over-informative referring expressions
How do we reconcile the idea that language is efficient with violations of efficiency in language use ("look at the yellow banana") and the ubiquity of ambiguous utterances?

Terms such as "redundant" and "over-informative" are commonly used to describe situations where people produce modifiers that do not restrict the extension of a noun phrase, e.g. "blue cup" when only one cup is salient, and thus the substring "cup" seems adequate to uniquely identify the target [@rubio-fernandez2021]. People do produce these non-restricting modifiers in reference tasks, especially for color, but this behavior seems to run counter to the idea of efficient language use. 

Formalizing claims of redundancy or over-informativity requires a definition of what would be minimally informative, which in turn depends on a commitment to a fully specified semantic-pragmatic system, at least for the range of utterances to be considered. In the more general case, this quickly gets quite thorny: for instance, if specificity implicatures are within the option space, are those calculated before or after informativeness is measured [@bergen]? One could sidestep the thorny theoretical by empirically measuring the information content of different utterances by how they shift the entropy of the distribution of inferred meanings [@degen20200406], but this does not scale up well in part due to issues with compositionality. 

The flip side of "redundancy" is ambiguity: many, many utterances are ambiguous. In general, strong contextual factors render the ambiguity a non-issue [@piantadosi2012], but this means we can't judge language outside of the physical and social context it is used in. Determining what is efficient language use in context requires not just analyzing phrases and their alternatives, but also how long utterances take to generate and comprehend, which may be highly contingent on contextual factors and conversational history.  

The idea that utterances should have "just enough" information has inspired a wealth of empirical research into what utterances people produce and what utterances people comprehend. By comparing these two halves of language use, we can determine how calibrated the utterances people produce are to what other people will understand. If calibration is reasonable, that would support an efficiency framework with minimal linking assumptions; if the calibration is not, we would need to invoke other assumptions (for instance, bottlenecks on production, goals such as politeness rather than just informativity) and then consider whether they are still parsimonious. 



### Bayesian pragmatics

Another broad coverage framework in cognitive science is modeling humans as Bayesian agents making resource rational choices. Within language, this tends to show up as a Bayesian pragmatic models, where (boundedly) rational Bayesian agents reason about each other to determine the meanings of utterances. 

A prominent model within Bayesian pragmatics, is the Rational Speech Acts (RSA) framework, an information-theoretic, computational framework for making quantitative predictions about pragmatic inferences in context [@goodman2016; @frank2012a]. The basic idea of the RSA family of models is to picture two interlocuters recursively reasoning about how the other would produce or interpret utterances, grounding out in a listener (or speaker) who behaves in a pre-specified "literal" way. 

Computational frameworks such as RSA provide a way to factor together different trade offs and determine their relative weights in a model [@goodman2016]. A softmax is taken over the scores of the options to produce a distribution of interpretations and utterances, with some parameters such as the degree of optimality fit based on data. This framework is usually run with one or two levels of recursion, where it tends to produce a reasonable fit to human experimental judgments, consistent with work finding that most people reason pragmatically at a low recursion depth [@franke2016]. 

RSA models have been used to predict some instances of ad hoc pragmatics as well as conventionalized pragmatic implicatures [@bergen;@degen20200406; @goodman2013]. Models generally include a utility or informativity term that relates to how well an utterance resolves uncertainty in favor of the target referent.  It is common to also include factors such as the prior likelihood of referring to each target (salience prior) and some cost on utterances where longer or more complex utterances are penalized [@goodman2016]. Some models also go beyond informativity, incorporating options to infer the question-under-discussion [@qing2016;@kao2014] or for speakers to balance informativity with politeness [@yoon2018a].

A full RSA model would incorporate all of these components and infer their weights. However, for tractability, usually only those features that are considered relevant to the domain of interest are included. Because of the flexible framework, it is possible to model many sources and levels of uncertainty, and then integrate out that uncertainty to make predictions, but also update on the sources of uncertainty in response to input. 

The RSA family of models is a specific instance of a larger trend in pragmatics and semantics towards more "fuzzy" meanings, either explicitly pragmatic or using neural models that also represent real-valued meanings [@erk]. 

$TODO mention that RSA has also been used in Bayesian word learning situations

#### The Challenge of Semantics
Perhaps the largest challenge to RSA models is the question of how to ground out the models in a "literal" listener or speaker. For the most part, RSA is tested in toy domains where the set of possible utterances is small and it is possible to enumerate a set of meanings [@frank2012a;@goodman2013;@bergen]. For instance, in some domains, a soft or continuous semantics is used to represent that some dimensions of meaning might be more strongly informative than others [@degen20200406]. This semantics supports the prediction of patterns of  "redundant" color adjective use in referring expressions. 

Soft semantics can run into conflict with compositionality: either every possible utterance must independently receive a degree of match with every possible object in the prior, or the prior needs to include rules for how to calculate the meaning of the whole from the specified meaning of parts.  In a later experiment of @degen20200406, typicality effects made compositional semantics not work, but the utterance space was small enough that each utterance could be treated individually. The issue of scaling from words to sentences holds across these "fuzzy" pragmatic approaches; one can just use sentence level meanings instead, but this risks throwing out compositional information and acting more like a bag of words model [@erk].  

 In less toy domains, there is not a satisfactory answer: some situations can be handled by empirically measuring likelihoods in an exhaustive ways, but this holistic approach is not compatible with incremental RSA [@cohn-gordon2018] or larger sets of utterances that require compositionality to be defined. Some work has used grounded neural language models for alternative generation and likelihood measures, which has scaling potential in domains that have the right grounded datasets [@monroe2015;@white2020;@cohn-gordon2018].  In order to extend RSA towards more realistic and open-ended scenarios, an important question to grapple with is what form of meaning (even at a computational level) will appropriately support pragmatic reasoning. 
 

 $TODO re-read the neural RSA stuff

### Information Theory 

A formalism that is used both in Bayesian pragmatics and efficiency work is information theory, that can serve as a way of connecting the ideas to concrete measures and predictions. Information theoretic measures such as entropy, surprisal, and rate distortion theory have been key to quantitative theories in computational work on language. Information theory based theoretical proofs and toy models have been applied to domains such as language evolution [@plotkin]. 

The ideas of information theory provides a link from functionalist accounts of language usage to the artifacts of language systems, by focusing on what the constraints are that would render the language systems we observe an optimal solution to the functional question of communication [@futrellhahn]. 
One advantage of information theory is that it provides ways to calculate measures of complexity in a mostly theory neutral way [@futrellhahn]. 

Measures derived from information theory such as surprisal, conditional entropy, and mututal information have been very productive in language science both for unifying aspects of language typology (ex. dependency locality) [@futrell2017] and for matching language processing (ex. surprisal theory and entropy reduction) [@hale2001; @levy2008; @hale2016]. 
The idea of rate distortion and a limited channel compressing a meaning through a message has been key to testing efficiency claims related to syntax, word order, and grammatical markers [@futrell2017; @mollica] 

There is also a connection between information theory and pragmatics, as RSA formulations are closely related to solutions to information-theoretic joint optimization between utility and effort [@zaslavyskyRDRSA]

One difficulty with applying information theoretic measures is that it requires a probability distribution to work with; thus, similarly to other frameworks, there are questions of what distributional language models or datasets to use to capture the baseline language. 


## Phenomena


The communication and conversation literature, especially with regard to referring expressions, has provided useful descriptive characterizations of how people communicate in naturalistic and experimental settings. For iterated reference games in particular, there is an accumulation of fairly consistent and reliable findings of reduction, convention, and partner-specificity. While there are consistently observable trends in the conversation literature broadly and in iterated reference games specifically, there has not been strong identification of necessary and sufficient conditions or dose-response relationships between circumstances (or experimental settings) and the size of the effects. Thus, there are not quantitative accounts for the phenemena. Instead, the effects tend to be characterized with verbal theories that posit causes.

It is difficult to directly test these theories as they often fail to make explicit predictions about what would happen under conditions other than those tested or what experiments would adjudicate between theories. Many of these theories present certain results as "special" but our question as we go will be to what extent these phenomena could be explained by the broader coverage theories of efficiency and rational communication.

As I go through different theories and phenomena, I will consider the available evidence, problematize the verbal theories, and attempt to see how the above approaches from computational psycholinguistics might be used to more formally model or subsume the empirical results. 

### Mentalizing and non-mentalizing approaches

One historically important distinction that recurs with conversation, and interactions between agents more generally, is whether and how agents track other agents internal states of knowledge and how this factors into their interaction. While an intuitively appealing distinction, it's not clear how to test this. 

One could build, for instance, model-based and model-free algorithms and then compare which better captures an observed phenomenon, but this seems to harken back to associationist versus rule-based accounts in linguistics, which don't seem as relevant now. These aren't opposites so much as points on a sprectrum and appearances may also be decieving -- what looks rule based could be instantiated in a non-symbolic, associationist way. On the other hand, a more sophisticated approach could look more associationist under performance load.

While is it not clear how to test these theories, it is still worth discussing the frameworks for historical reasons. 


#### Mentalizing tradition and "common ground"

The "mentalizing" tradition treats humans as representing other humans as agents with internal states that include knowledge and goals.  Within this broad school, there is variation in how these representations are implemented, how information gets added or modified, what exactly is tracked, and when representations (versus heuristics) are used. 

Within this tradition, many use the term "common ground" to refer to knowledge that two agents share. In some cases, it is used in a pre-theoretic way to mean roughly "things you think another person will understand and won't be surprised if you reference" [@leung2023; @garrison2022]. For instance,  @hanna2003 defines common ground as the "mutual knowledge, beliefs, and assumptions" held by the interlocuters. This meaning is roughly comparably to "givenness" in other domains [@fay2010].

However, "common ground" is also sometimes used in a theoretically loaded way, originating from the privileged versus mutual versus common knowledge framework [@clark1986]. Under this usage, "common ground" is defined via infinite recursion in knowing that the other person knows that the first person knows that ...; this is the usage that comes up in formal semantics where many things may be introduced to common ground via accommodation [@horton1996; @pickering2004].In practice, humans don't tend to do more than a couple layers of recursion in their pragmatic reasoning [@franke2016]. Thus, it is generally not important to distinguish knowledge types at deeper recursion levels than mutual knowledge that both people know to be mutual. 

Even if we accept that common ground has grown away from it's formal semantic roots to just be a convenient shorthand for "mutual knowledge", there is still a question of how agents know (or decide) what is mutually known. Many approaches have tried to characterize when something is mutually known [@horton1996;@clark1986;@brown-schmidt2012]. This has predominately taken a deterministic approach with rules such as "if it's in shared visual presence, it's mutually known". Visual presence may be a good heuristic, but it seems like whether something is mutually known may be better represented in a more graded way. 

These terms seem to be easily subsumed within a Bayesian inference and Bayesian pragmatics framework. While the "mentalizing" approach places special emphasis on "common ground", it's unclear whether this form of modeling another's knowledge should be treated differently from cases where one models another's knowledge that one does not personally have. For instance, in deciding who to learn from, someone might determine that another agent knows what's behind a door and then use this information to for instance, interpret a quantifier like some.  (TODO cite some RSA stuff for this) 

Another implication from the Bayesian approach is that we do not need to deal with deterministic rules and can instead reason under uncertainty. This may be useful for accounting for hedging behavior where there seems to be uncertainty over what an interlocuter will understand. Joint updating can also help for times when something was initially thought to be likely in the shared prior, but then new information decreases this likelihood. The framework of flexible inference and probabilistic knowledge states is a powerful tool. 

#### Non-mentalizing approach: Interactive alignment theory

In contrast to mentalizing approaches, "interactive alignment theory" attempts to explain how people can successfully collaborate on reference tasks without reasoning about each other's mental states [@pickering2004; @gandolfi2022]. The motivation for non-mentalizing accounts is the apparent difficulty of mentalizing, coming from accounts such as naive egocentrism (which will be discussed later). Given that humans reason socially about each other readily and from a young age [@rakoczy2022], it's not clear how well the motivation for a non-mentalizing approach holds up.

Regardless, at the time, there was desire for an approach to explain communication and coordination behavior without positing explicit reasoning about other minds, because it was that was too computationally expensive and slow.  Under this framework, [@pickering2004; @gandolfi2022] try to account for observed alignment between interlocuters by extending ideas from structural priming. 

Structural priming occurs when processing a grammatical structure (ex DO construction) increases the likelihood of expressing an idea using that structure rather than an alternative (producing a double object rather than a prepositional object construction) [@tooley]. In production, this occurs even when there is not lexical overlap (ex. different verbs), but is increased if there is lexical overlap. A similar effect occurs in comprehension, but it seems to require the same lexical head item [@tooley]. Many potential mechanisms behind structural priming have been suggested, but there is not a consensus. While typically observed in controlled settings, the tendency to reuse constructions to express ideas is also observed in dialogue [@pickeringferreira]. Some other forms of alignment is dialogue can be observed in natural corpora, such as style alignment between interlocuters on Twitter [@doyletwitter], although the accomodation direction is moderated by social factors, which seems to complicate automaticity accounts, and lexical repetition, but not category alignment, for non-content word categories in Twitter and Switchboard corprora [@doyleotherone]. 

@pickering2004 claims that the alignment occurs via "priming" and is "resource-free and automatic", without providing a further explanation of what this means or how this works in terms of memory and processing. Unfortunately, as expressed, interactive alignment theory doesn't provide an algorithmic or mechanistic level theory. 

There are a few issues with this theory. For one,  it is unclear that structural priming would predict this cross-level trickle-up or trickle-down effect that is key to interactive alignment; the claim that people tend to say "the ball that's red" after their partner says "the block that's blue" is quite different from a claim that this also aligns their "situation models". Some empirical work on alignment also makes claims of automaticity, but Another issue is that it's really hard to test for intent (or lack of);  for instance, repetition could be due to some sort of "priming", or explicit reasoning, or production-side ease of use constraints (CITE MACDONALD). 
Perhaps the largest problem with interactive alignment theory is that it does not account for one of the key features of iterated reference games:  that people converge to conventionalized referring expressions that evolve and shorten after both people understand each others expressions. Thus, one requires an explanation for change, not just repetition or mimicking. To my knowledge, interactive alignment does not have an explanation for this, in part perhaps because their studies tend to be of a different sort. The "common ground" tradition generally using asymmetric director/matcher designs (dating back to at least \citet{krauss1966]) and the "interactive alignment" traditions using symmetric designs such as the `maze' task. Thus it is possible the two approaches are build around trying to explain differing sets of experimental results. 


Figuring out exactly what alignment happens in conversation may well be worthwhile, but it does not seem that useful for the phenomena in iterated reference games in particular. As the iterated reference game is mostly used within the mentalizing tradition, most of the theories discussed will also belong to that tradition. That said, even within mentalizing theories, the actual implementations are unlikely to be full inference. One way to explore this would be with approximations of full Bayesian inference in the resource-rationality tradition or with information theoretic limits on memory capacity that don't allow for full partner representation. 


### Partner specificity

One key phenomenon from iterated reference games is that describers change their behavior when the set of matchers changes, usually shifting back to longer descriptions when a new matcher is introduced. This change in behavior is described as "partner-specificity", with the idea being that the conventional names developed with one partner as specific to that partnership [@brennan1996; @metzing2003a; @hawkins2021a]. The idea of partner-specificity is also referenced with regard to how different pairs diverge to different names for the targets [@hawkins2020b]. Partner specificity is part of the mentalizing tradition and assumes that partners (and their background and knowledge states) are being represented in the minds of speakers. The form of the representation is not explicitly stated, so these models could be compatible with heuristic or distributed representations, but include explicit thinking about the audience and are incompatible with the non-mentalizing "priming" account. 

Empirical evidence from experiments where one director talks with multiple partners suggests that people do "partial pooling" over their partners [@hawkins2021; @yoon2014]. That is, a speaker A will show some variation in their expressions when talking to partner B versus partner C, but there will be some generalization between partners as well, so that A talking with B is more like A talking with C than D talking to E. When coupled with a tendency for descriptions to shorten within a pair, this leads to a jagged pattern of reference length: when switching to a new partner, speakers use longer utterances, but not as long as their initial utterance with their first partner [@yoon2019]. 

This pattern could be efficient if the context from the initial utterances is requisite to understand the later parts. The jagged pattern in particular is suggestive of a mix of speaker production effort and shaping the matcher's lexicon. If we consider the elaborated and shortened forms of the concepts (ex "arms up, like a goalie diving for a ball" versus "goalie") to be synonyms (in the same way chimp and chimpanzee are synonyms), then the switch to short form after establishment and the temporary switch back with a new listener could be explained under a uniform information density model, provided that the longer form occurs in a context when it is more surprising and informative [CITE GIBSON paper]. This raises the questions of how to think about information in reference games, when in some sense, at most 3.5 bits of information are needed for a 12 way choice. We will return to the issues of surprisal and informativity in reference games at the end of the introduction. 

Partial pooling and partner specificity can be instantiated in a hierarchical model of Bayesian pragmatics, such as those introduced in CHAI or lexical uncertainty models. Testing out these model frameworks with natural language data is not yet tractable due to the need to figure out computational and semantic issues, but the models seem to provide coverage at least in theory. 


How can we think of partner specificity from an information-theroretic lens? One approach might be to think about what the mutual information is between the conversation history, the current utterance, and the visual context of targets. Within a partnership, the conversation history can serve as a sort of encoder that allows later conversational elements to use a more efficient coding to map between language and referent. Under partner specificity, one would say that condition on conversation history, the target and convention predict each other, but that conditioned on no history or a different conversation history they would not predict each other. This abstracts over having a model of how conversation history unfolds, but it's at least an operationalization that could be testable using machine learning models. 


### Audience design & effort sharing

One set of theories in communication that are often tested and explored with iterated reference games have to do with how two (or more) people split the communication load. 

One relevant concept is "audience design", the idea that speakers seem to be sensitive to the knowledge state of their listener and say things that are easy for the listeners to comprehend. This seems to occur sometimes in everyday life where we speak differently to a 5 year old than to an adult, or explain things differently to a colleague than to a lay person. Like many technical terms used here, "audience design" means different things in different contexts. However, despite the introspection that we design utterances for the audience in some cases, it is difficult to identify if it is happening intentionally in referring games. 

Confusingly, the phrase "audience design" sometimes implies intention on the part of the speaker [@horton2002a; @horton2005], and sometimes is used when utterances are constructed based on what's easy for the speaker, and listener ease is a side effect [@horton1996; @rogers2013; @macdonald2013]. For instance, audience design could both occur in times when the speaker gives an elaborated description to a naive listener (inferred to be intentional if contrastive with their description to a non-naive listener), but speakers may also tend to start descriptions with given material which is both more accessible to the speaker and convenient for the listener. 

Audience design is sometimes used very broadly [@ferreiravic] when production choices make it easy for listeners to comprehend, even if this is not customized to the listener. In a very broad sense, efficiency pressures for things like uniform information density could be construced as audience design in this broad sense. 
Beyond iterated reference games, speakers do behave differently depending on the listener; speakers tell a story differently when retelling it to the same listener versus when telling the story again to a new listener [@galatibrennan]. One question here is with goals -- cite Richard RSA paper about tradeoffs between effort and goal that may differ  

Intention versus side-effect are difficult to distinguish between because speakers and listeners often share recent context, find the same things salient, and linguistically what is easier to produce is often easier to process. Thus, disentangling speaker and listener ease may require careful experimental designs where ease of production and ease of comprehension are separated [@ferreira2004]. 



Questions around audience design are related to larger issues of how interlocuters split the communicative burden with one another. Depending on the task and the communication modality, there may be many options for how to balance the communicative load  [@clark1986; @fay2010; @foxtree2013]. For instance, a listener could describe what options they see or otherwise prompt the speaker. We might expect the load splitting to vary based on the capacities of the interlocuters (ex. a speaker might craft their utterances more when talking to a child versus an adult) and the capacities of the channels (ex. speakers may use different approaches if listeners can interrupt). 

While much of the work on iterated reference games and communication more generally has focused on interactions that are dyadic at any given time, much conversation in the real world takes place in larger groups. Multi-way conversations complicate the theories of audience design and partner specificity by introducing a larger audience of more partners. Two main questions are whether speakers "aim low" or "aim high" in balancing the needs of the listeners and whether speakers track individual listeners or an aggregate [@yoon2014]. 

Empirical results indicate that speakers are sensitive to the knowledge states of listeners in a gradient way. Describers seem to track the knowledge states of different matchers independently when they alternate between addressing matchers [@yoon2017]. When addressing a group of matchers with disparate knowledge levels all at once, speakers generally give descriptions that are fairly similar to what they give only naive listeners [@yoon2017]. However, there is also some gradient, where descriptions vary based on the proportion of naive listeners in groups of up to 4 addressees [@yoon2019]. With pairs of listeners who differ both in their background knowledge and in what context they are seeing the target in, speakers produce descriptions that are sensitive to the interaction between background knowledge and distinctiveness of the target in context [@yoon2019a]. 

 Speakers also use strategies in group contexts that don't occur as often in dyadic contexts, such as referring to a target with both the name that one person will understand and a elaborated description that will help another person get on the same page [@yoon2018]. The ability to track partner's knowledge states presumably would degrade as groups got bigger, but this paradigm has not been used for groups large enough for this to happen. 

One angle on larger groups is network structures, where (non-linguistic) convention formation has been studied on networks of up to 50 people [@guilbeault2021]. In this communication game with targets varying over continuous space, large groups tend to end up with fairly consistent category boundaries across independent networks, while small networks can support more idiosyncratic category boundaries. This work is suggestive that there may be group-size and group/network-structure dependencies on what sort of conventions arise. There has been some work on group and network designs in traditional iterated reference games, but only on relatively small groups. 

One question related to partner specificity and audience design is whether the observed behavior is optimal. People are generally fairly pragmatic in their communication, so we might think that using different descriptions based on the composition of listeners is adaptive and calibrated. Speakers behave as if the descriptions that are appropriate to give vary based on the listeners knowledge state and their shared conversation history. 

One source of evidence about the potential optimality is whether other people (naïve matchers) can understand the descriptions, and whether this varies by circumstance. This has not been addressed from the efficiency and optimality angle, but the role of dialogue and conversational history has been studied. Naïve matchers tend to do better the more their observation history resembles that of the original conversation---when hearing descriptions in order instead of in reverse order [@murfitt2001], when listening to the entire game instead of starting in the third round [@schober1989], and when seeing yoked trials from a single game rather than trials sampled across 10 games [@hawkins2023a]. Descriptions produced in dialogue are easier to understand than those produced in monologue [@murfitt2001]. The gradient suggests that some of the development in descriptions may be adaptive, but there has not been work grappling with whether the far above chance performance of naïve matchers poses problems for audience design theories.

It certainly suggests that from a purely audience design listener-focused perspective, speakers are not efficient, in that to the extent that new people can understand later utterances without context, a counterfactual more rapid adoption of short forms is likely to be able achieve a certain level of accuracy just as well as the observed pattern. This is an area that could benefit from empirical work around what the optimal pattern could be. There are also some alternative auxiliary hypotheses that could save the efficiency idea before we are forced to conclude that humans are miscalibrated. One possibility is that the communicative bottleneck is firmly on the production side -- speakers are doing the best they can to rapidly produce descriptions, and producing more succinct descriptions earlier would be too costly in terms of effort or time. Another possibility is that social norms and task dynamics dissuade the use of short form descriptions even if they are likely to be understood, perhaps the initial descriptions are more polite, or perhaps people are cautious in their efficiency/accuracy trade-offs. 

Bayesian pragmatic models could be extended to cover situations discussed here. Rather than just communicate pragmatically with one person, balancing multiple people's needs would require balancing different goals. Again the difficulty of specifying base interpretations and compositionality and reasoning may pose some difficulties, but a toy model of the situation could work. Similarly, a lexical uncertainty Bayesian pragmatics model would be an approach to capturing the new listener behavior in eavesdropper scenarios. In terms of effort splitting, that could also at least in theory be represented by changing RSA parameters such as depth of reasoning, starting lexical semantics, or cost functions. 

### Convention formation 
One of the key phenomena of interest with iterated reference games is that
over repetitions with the same partner, dyads tend to form shared "conventions" (also called "conversational pacts") about how to refer to the initially ambiguous targets. These conventions tend to be partner- and context-specific: changes in the speaker, audience members, or changes in the context can all license the use of a new description [@metzing2003a; @ibarra2016;@yoon2014]. Absent these changes, pairs tend to stick near the semantic space of successful descriptions. 

What exactly does convention formation refer to? There is ambiguity about what level of specificity convention formation and conceptual pacts refer to. It could be on the lexical level, such as calling a figure "ballerina". It could be conceptualizing the figure as a ballet dancer with a tutu (manifesting in descriptions with semantic association, but not lexical overlap, such as "ballerina" and "dancing in a tutu"). It could also be a general paradigm for how to describe figures, such as in terms as humans in different postures.  @horton2002a distinguish between "lexical entrainment" when the same words are reused, and "conceptual similarity" when there is broader similarity that does not repeat the same words. These levels often co-occur, but in order to computationally quantify the phenomenon of convention formation, we have to make choices about how to operationalize the similarity:  is it word overlap, lemma overlap, distance in semantic space, or something else. 

In addition to convention indexing the stickiness of some properities of the description, there is also a pattern of change from typically a description of a set of features to a more holistic label. Typically, in convention formation, holistic or analogic descriptions are the ones that stick [@clark1986], but this isn't absolute. Groups can successfully coordinate on reference using many different types of names, including ones that pick up on low-level or meta-level features. The range of successful options makes explaining convention formation harder, and suggests suggests a strong path dependency for how reduced utterances evolve, potentially influenced by factors such as relationships and humor value.  How to quantify this transition or model why it occurs are also open problems. 

The semantic meaning of a description is not a priori related to its length, but these two features empirically tend to correlate in iterated reference games [@hawkins2020b].  Thus "reduction" or the shortening of utterances is sometimes used as a shorthand and measurement proxy for the semantic changes [@clark1986; @hawkins2021; @garrison], and @bovet considers it a measure of common ground. Convention and reduction are sometimes conflated with partner-specificity, as these phenomena often co-occur with different pairs forming different conventions and changes in group composition leading to (temporarily) longer descriptions [@clark1986;@wilkes-gibbs1992]. Better tools for measuring semantic distance separate from length may help address the theoretical issues of how entangled these concepts are. For instance, when a describer gives a more elaborated description based around the same conceptualization for a new addressee, where does that fall in terms of conventionalization? 

It remains an empirical question whether the shortening of utterances, convention formation, and partner-specificity of descriptions are inseparable or merely occur together in the experimental paradigms considered in the literature. 

From an information-theoretic perspective, we can think of convention formation as convergence towards a modified encoding that is more efficient at representing the specifc set of target meetings that the baseline language. These are not meanings that are not usually commonly needed and thus don't have initially high codeability, but over local usage, a (temporary) warp of the meanings can be achieved that is locally more optomized to express the target meanings. 

#### CHAI models

Scaling up RSA to handle reference games requires solving at least two problems. One is specifying a semantics system that can handle the abstract, metaphoric, and parts-based descriptions that are used -- this could be seen as the problem of accounting for initial reference. 

Secondly, one must explain how to go from one successful utterance to a different (often shorter) utterance. One RSA-style model that attempts to explain why multi-part descriptions are produced initially, but shorter descriptions are produced later is CHAI,  a framework to bridge different levels of convention formation [@hawkins2021].

CHAI incorporates parameterized hierarchical uncertainty over lexica that allow for variability in how words will be interpreted that can be integrated over. Listeners' lexica are not fully known which accounts for background differences that may be shared by a sub-population and differences from communication history that may be individual-specific. The results of inference update these priors, and propagate the new information to both the individual and group lexical representations. CHAI can qualitatively account for various convention-formation phenomena in toy systems [@hawkins2021].

CHAI's explanation for reduction is consistent with the ambiguity arguments of @piantadosi2012: initially the context is not sufficiently constraining to resolve the ambiguity of a short utterance, so multiple descriptive pieces are needed to triangulate the meaning, but as conversational history accrues, the context is sufficient to disambiguate the shorter description. 

In toy models of interlocuters playing a reference game with soft semantics, initial utterances use multiple properties to collectively increase the degree of certainty in the target. This successful reference then shapes the prior over word meanings, until the degree of certainty afforded by only one word is sufficient to pick out a referent. 

The same approach CHAI uses to generalize from individuals to groups and populations could also be used to generalize across stimuli, if one could get the baseline semantics worked out. Then, a successful reference (like "man with arms up") would not only update the meaning of that phrase or components, but could also lend weight to the overhypothesis about using human and body part based descriptions, and thus update the speaker's beliefs about the listener's semantics for the words "head" and "leg". 

### Developmental work

One angle to understanding linguistic phenemena is to look at their developmental trajectory to understand when the phenomena arises and how it changes across development. 

There have been a limited number of direct studies of iterated references games with children, although there is a much wider body of work on young children's communicative and pragmatic abilities. 

One influential early study suggested that 4-5-year-old preschoolers struggle with child-child referential communication [@glucksberg1966]. In their paradigm, one child was given a set of 6 blocks in a specific order. Their task was to describe the image on each block so their partner could pick out their corresponding block. As children described and selected blocks, they stacked them on pegs. While 4-5-year-old children succeeded on practice trials with familiar shapes and visual access to each other's blocks, children failed on critical trials where the blocks had abstract drawings and there was no visual access. Even after multiple rounds with the same images, children were not able to correctly order the blocks. @glucksberg1966 attributed children's communicative failures to their production of ego-centric descriptions that did not account for the other child's perspective.  Similar experiments with older children indicated a gradual improvement through adolescence both for initial accuracy and for the increase in accuracy across repetitions. Still, even the 9th grade sample was noticeably worse than the adult college student sample [@glucksberg1967; @krauss1969].

Since @glucksberg1966, few studies have revisited the question of whether children can successfully communicate in an iterated reference game. In one study, 8-10-year-olds exhibited adult-like patterns of increasing accuracy, increasing speed, and shorter descriptions across repetitions, but children’s accuracy was still far below adult performance and highly variable between dyads [@branigan2016]. 4-6-year-olds successfully used conventionalized gestures with their partners in an iterated reference game where children could only use gestures to communicate [@bohn2019]. 4-8-year-old children succeeded at playing an iterated reference game with a parent using a simple, child-friendly tablet-based task [@leung2024]. In this task, even 4-year-olds had an initial accuracy above 80%, which rose to above 90% in later repetitions [@leung2024]. 

One issue that arises is developmental work is assessing whether the paradigms are measuring the abilities of interest or whether task demands or cognitive limitations are masking nascent abilities. 

The overall trend in developmental work has been discovering evidence of abilities emerging earlier than previously thought, due to better methods and designs that require fewer additional cognitive resources. 

In pragmatic communication, a number of early pragmatic abilities have been documented. Preschool-aged children are faster to select a target when it is referred to in a consistent way [@graham2014; @matthews2010] and 6-year-olds are more likely to use consistent referential expressions when their partner is consistent [@koymen2014]. Further, preschool-aged children adapt the informativeness of their referential expressions based on the visual content available to their interlocutor [@matthews2006;@nadig2002;@nilsen2009], and by age 5, children integrate perspectival information into their comprehension of utterances [@sanjuan2015]. These studies are contra an earlier belief that children were very egocentric TODO DISCUSS

By 5 years old, children are sensitive to over- and under-informative utterances, asking for clarification on some under-informative utterances and taking longer to make selections on over-informative utterances [@morisseau2013].  Children ages 3 to 5 show sensitivity to referential pacts, in protesting the breaking of a pact, although they sometimes protest even when a new speaker uses a new term [@matthews2010], in contrast to adults who allow new speakers to form new pacts [@metzing2003a]. In a test of both context and partner-specificity (modeled on @brennan1996), 6 year olds showed the adult-like pattern of maintaining the same terms with a partner even when a context change rendered them overinformative, while 4 year olds struggled more on the task and did not show partner-specificity [@koymen2014].  	In addition to partner-specificity, adults are also sensitive to the context and whether distractor items are close or far. Evidence for children is mixed, with @abbot-smith2016 finding some signs of sensitivity to context in 2 and a half year olds, but in a different paradigm 4-8 year old children did not appropriately modulate labels to familiar objects based on context [@leung2023].

While children are sensitive to others’ perspectives, they still struggle to appropriately tailor the specificity of their utterances to the visual context, often resulting in under-informative utterances [@matthews2012; @leung2024].  When children must describe one of two very similar images, 4 and 5-year-olds sometimes neglect to mention the relevant features, although they do better when playing in an interactive game than when not [@grigoroglou2019]. This seeming confusing between naming something and distinguishing it in context seems to be the communicative that lags. 


What could psycholinguistic frameworks add to our understanding of developmental pragmatics? 
If we had a computational model of adult performance, the question would be what aspects to change or restrict to approximate child behavior. For an RSA type model, we could consider a lower optimization parameter, or reducing the amount of computation (sampling fewer options). Children might also do a similar process, but with a different size and baseline semantics in the lexicon. Would their updates in a repeated model be smaller or bigger?  Even if we can't fit the model, the modeling formalism suggests ways of thinking about the differences between children and adults in a dimensional way. 

If we take efficiency to mean an optimal tradeoff between expressivity and effort, then children might have different weightings between the two, ending up on a different frontier or a different part of the frontier. For instance, cogntive capacity constraints, or things like working memory or executive control could mean that certain types of utterances are particularly effortful, and thus shift the optimal curve to include less expressive utterances. For child -- adult dyads, the shift in speaker / listener capacity may be substantially different than for adult - adult dyads, rendering different approaches more efficient. This may be difficult to test since it would require figuring how where the bottlenecks are empirically, or having good enough models to compare fits to the data. 

Maybe we can concieve of communication channels involving children as being extra noisy or as having more limited channel capacity. 

### Incremental approaches to processing and production

Another angle from which to view reference is from the fine grained time course. As a referring expression is incrementally processed, what is the listener doing? How early do effects related to speaker identity or pragmatics occur? 

The typically approach to understanding the unfolding of comprehension in real time is via visual world eye tracking where looks are interpreted as meaning to potential targets. Alternative methods to get at incremental interpretation and processing difficulty can also be used. 

One idea that visual world approaches to reference try to address is whether there is an initial stage that differs from the final resolution. For instance, certain influences like the literal meaning of the utterance might be available sooner than pragmatics or more contextualized interpretations.  This is sometimes characterized as "top-down" versus "bottom-up" but there may also be different sources such as linguistic context or social context or visual access.

The relative balance and time course of top-down and bottom-up influences has been a big question in psycholinguistics and neurolinguistics for a long time [@gwilliams2022;@tanenhaus1995;@horton2005;@horton1996]. One debate in particular, in the (non-iterated) reference game literature specifically concerned the role of egocentrism in the early stages of linguistic processing. One side of the debate was the Egocentric Anchoring and Adjustment theory, where @keysar2000 argued for an initially egocentric perspective on the basis that people often initially look at objects that are good matches to a description even if the object is not mutually visible to the speaker [see also @hortonkeysar1996, @keysar2003, @barrkeysar2007]. In particular, this theory claims a two-stage model where there is an initially (completely) egocentric perspective that can later be overcome, in contrast to the (much less controversial) idea that there is a general egocentric bias where one of the sources of information is egocentric but it can be in parallel to theory of mind information [@rubio-fernandez]. The ego-centric first claim rests on a couple dubious linking hypotheses: that if people consider an interlocuters perspective, their prior should be that the interlocuter only refers to mutually known things;  and separately, that looking at an object is a sign that it is considered a potential referent [eye-tracking data is widely interpreted this way, but there is evidence that this proxy is only approximate, @degena]. Their studies also always had the egocentric-only lure be extremely salient, by making it by far the best match to the description. 

The counterpoint to initial ego-centrism presented by [@hanna2003] is a constraint-based theory where many factors can play into comprehension [ see also Nadig & Sedivy 2002, Hanna, Tanenhaus & Trueswell 2003, Hanna & Tanenhaus 2004, Tanenhaus & Brown-Schmidt 2008] . Many factors may influence language production and comprehension, to varying extents, and on differing time courses. Their studies use egocentric lures that are equivalently good to the shared visibility target and find early perspective taking, and confirm this with other experiments in different paradigms. TODO more citations

The larger picture of language processing and neuroscience strongly suggests that context information (at least from linguistic context) is used to predict upcoming linguistic material, and thus that "top-down" information can affect even early stages of linguistic processing such as phoneme identification and lexical processing [@gwilliamsdavis, @gwilliams]. Predictive coding is a theory with good coverage of neural evidence in many domains, including language, with language processing regions seemingly sensitive to both lexical and structural information in predicting upcoming words [@shainfmri].  However, we might still wonder if earlier behavioral readouts are more influenced by perceptual information and less pragmatic, or if cognitive load also sways the balance of influence. 


### Production constraints

Compared to the theoretic landscape around psycholinguistic processing, production is much less studied because it's a lot harder to study experimentally. 

There is agreement that production requires conceptualization, formulation, and articulation, but that is about all that is agreed upon [@burki]. From interference studies, we can get some sense of when certain elements in sentences are planned [CITE]. On a word level, the phonological realization of words that are more frequent or usually appear in more predictible contexts is reduced relative to words that usually convey more information [@burki]. This could be consistent with either a production facilitation account or an audience design account -- speaker and listener language statistics are similar so it is difficult ot disentangle. For production beyond the scale of single words, that are just more questions, including what the planning looks like, how the time courses of different stages of production may overlap, and what size and types of units are stored in memory [@burki]. There's a lot we don't know about the mechanics of production even in situations with less context-sensivity than iterated reference games. 

As with behavioral measures, neuroscience measures are also used more for processing than for production and articulatory processes are better studied than the higher level planning processes. FMRI studies indicate that language production tends to activate the same regions as language processing (unsurprisingly), but these regions are especially active during phrase structure building, suggesting that production may have higher costs than comprehension [@hu]. However, fMRI does not have precise time course resolution, so it can't resolve questions of how information flows in the brain. 

The increased load from production is consistent with accounts that suggest that utterance design (and language evolution) are substantially shaped by biases to easy production. @macdonald2013 points out three production biases: easy first, plan reuse, and reduce interference that could explain some patterns of utterance production, including in reference games [@macdonald2013]. 

One approach to identifying speaker-side difficulties in iterated reference games is to lok for disfluences [@yoon2014]. Intuitively, producing descriptions of abstract figures is difficult and there may be load based on task difficulty that leads to non-optimal productions (ex using "square head" as part of a description when it is not diagnostic) that are reminiscent of children's describe/identify difficulties. 

There are approaches one could take to try to understand more what production-side pressures are, including time-course locked measures such as eye-tracking and disfluency analysis. Carefully controlled studies and comparisons to monolog conditions may also help. Varying time pressure or pre-articulation planning time could also be used to help sort out what's going on [@horton1996]. But as the larger questions around production generally show, this is hard to study and may require very careful and clever experiment designs. 

What do the broader coverage frameworks have to say about production? Production-side constraints are one of the factors posited to drive linguistic efficiency, but there aren't fleshed out predictions about speakers would or wouldn't say. In general RSA operates on a level of abstraction that only considers entire utterances and so only considers production cost in terms of the utterance sampling procedure (if not all options are considered) and the costs assigned to each utterance. However, given that most iterated reference games allow the speaker to keep talking, one could (again, in theory) adapt incremental RSA (TODO CITE) to explain potential order effects within what parts of descriptions are produced first. 

One information-theoretic computational-level model of incremental language production comes from @futrellinfotheoryproduction. This model applies the Rate Distorition Theory of Control to production, suggesting a trade-off between incremental steps that are good for the communicative goal (ex. being informative) with what is easy to produce, that is what is more automatic and predictable. As with other information-theoretic models, it has good explanations in toy or qualitative domains for explaining production ordering preferences, the use of filled pauses, and good-enough word production. 

## Where does this leave us? 

A core theoretical question is whether the observed patterns of reduction, convention, and partner-specificity require "special" mechanisms, or whether these results can sufficiently be explained by broader coverage theories of language production and comprehension more generally. 
	
### Efficiency 
Sometimes, judging whether something is efficient or not may be clear cut, if all reasonable sets of assumptions return the same result. It is perhaps easier to judge something to be inefficient if there is a shorter alternative that is both easier to produce and easier to comprehend. In the general case, however, efficiency is very hard to cache out in specific predictions because of the many time scales the pressures operate on. What's efficient for an utterance in isolation may not be efficient when considered over an entire life of language use. Thus, the efficiency framework is not directly testable, but it's goodness as a theory instead relies on the parsimony of the linking theories that are required to meld it to the data. 

The formation of conversational pacts is often characterized as efficient, but this claim has not been cashed out in formal models like those described above [@clark1986;@hawkins2020b]. "Efficiency" is an informal description of these pacts that captures that shorter expressions are *more* efficient, but a given shorted expression could still be mis-calibrated to a particular situation. It could be too short, leading to misunderstanding, or still longer than it needs to be for effective communication. Mis-calibration of this type could contradict claims about partner specificity of reduction, but would not have to. Communicators could intend to be optimally calibrated but run into production difficulties, masking their competence. Either way, current claims of efficiency in conversation do not connect directly with the formal claims of optimal efficiency in the “language design” literature, and it is unknown whether speakers and listeners are calibrated or not. 

Even with a specified task goal (communicate the target to a partner), what we tell people and what their actual utility function is are not the same. It's still a conversation between people so communication norms may also play a role, and that's difficult to control while retaining naturalism. 

There are some open questions that are testable, mostly focused on figuring out what sorts of linking hypotheses would be required for the behavior to be (mostly) efficient. 

One is figuring out how understandable utterances are from different points in the conversation, to basically test the idea that speakers are reducing "as fast as possible" for listeners; that is, both that extra words in an utterance are adding utility (adding information, adding certainty), and that the context of earlier utterances (and their repetition) is necessary for understanding later utterances (i.e. reducing faster would negatively impact accuracy). These are addressable questions, both with models and information theory applied to utterances and with testing new matchers on manipulated samples or orders of utterances.

The other issue is trying to get a handle on production-side demands. If speaker's have the hard task, then perhaps what they say is mostly driven by ease of planning. This is harder to test, but one could do monolog studies and dialog studies with eye-tracking and time course measures to try to get at it in more fine grained detail. 


Generally efficiency is usually applied to language the culturally evolved system based out of pressures that apply at each step. But it doesn't actually require that the individual steps be fully at the frontier, merely that there be enough pressure towards expressivity and ease overall that the system shifts in this direction. So, even if it turns out that people really don't seem efficient at this task, it doesn't hurt the efficiency framework that much because this task may be substantially out of distribution and thus, people's behavior on it is not shaping language use on a large scale. 


### Bayesian

Bayesian pragmatics is a very promising large-scale framework for explaining a lot of linguistic behavior in context and incorporating history and non-linguistic context into a model of utterance production and comprehension. The main challenge is figuring out how to scale up to handle the natural language that comes up in reference games. 

There are also some modeling considerations for how to extend models to deal with different types of data -- how to deal with multiple listeners simultaneously, how to abstract across items to learn conceputal paradigms (i.e. abstracting from items to an approach of describing images in terms of what the person is doing). One question that comes up with bayesian pragmatic models is how many free parameters they have and whether one is actually getting a parsimonious model with broad coverage, or just a set of related models very tuned to individual datasets. This is a broad issue in modeling and the closer we can get to a generative or cognitive model (even if fairly abstracted) the better. 

So one way of making progress and seeing how broadly Bayesian models can be applied would be extending the existing models for a wider variety of designs.
Group communication, either in the form of one speaker - multiple listeners [@yoon2014;@yoon2018;@yoon2019] or network structures [@hawkins2021a], poses a challenge as there is not yet a non-dyadic extension of RSA that can do partial pooling across listeners and jointly optimize for the responses of multiple interlocuters. It should be possible to design extensions to CHAI to accomodate different group structures. 

However, it would still lead to questions of whether the small-scale models can predict the patterns see in natural language, full scale experiments. And that requires solving problems related to the open vocabulary. How do you set baseline (literal) meanings for any utterance someone might produce, and how do you allow those to update in a sensible way? With toy models, one can do composition semantics and update based on the compositionality. While we could ground semantics in some neural model (ex. in some sort of VLM) that doesn't give composition units that can be individually updated. Thus, I think some of the challenge of getting a robust test of Bayesian pragmatics models requires a lot of NLP and ML engineering. 

CHAI, while not a full explanation for the full patterns of real-world data, is a big step forward in at least providing a framework that actually explains why reduction would be optimal. It remains to be seen whether RSA-style models can predict the slope of reduction and the content of words that stay versus drop, but I believe the attempt would push forward our understanding of pragmatics and communication. Even without a cached out model, this approaches can inform how we think about experiments and results. 


### Information theory

Unlike efficiency and Bayesian pragmatics which are frameworks, information theory is more of a tool. It's robust to see that in iterated reference games, the utterances tend to get shorter, but what's actually going on with the language? In order to quantify that, it's useful to have some sort of metrics to use. One could theorize that words that are more informative are more likely to stick around and become the conventions. To test this, one would need a measure of "information" to apply, which may now be possible to test using computational models of language and stimuli. 

Information theory also provides measures for trying to understand how context supports understanding. This could be to formalize ideas of common ground by considering the joint information between the conversation history (as the common ground) and the current utterance. Again, to measure this at scale we would need models to approximate the information, but there are now models that could be used. 

The idea of task relevant information also makes this an interesting place to apply linguistic measures of information theory. For normal psycholinguistic texts, information theoretic predictors like surprisal or entropy reduction have substantial predictive value on processing difficulty as indexed by measures of reading time (or neural signals) TODO CITE. While surprisal is a measure of information, we might think that it's not the same as how many useful bits of information are conveyed. (Gibberish is quite high surprisal, but low information.)

One way that information theory might usefully frame what happens in iterated reference games is that the language is adapting to the specific task of optimally coding the target options. An optimal code would only need 3.5 bits to express each of the 12 options (a common number of options in iterated reference games). Many more bits than this of natural language are used in early rounds -- suggesting that initially standard natural language is not a good fit for this task. Some of this language is conveying task-relevant information, just in a wordy way, while other parts may be not-task relevant at all (ex: describing features that do not vary across targets). Over time, people probably both drop some of the filler and identify the task-relevant components, but they also develop a more efficient code for those features. This formulation makes some testable predictions about the entropy of distributions over utterances at different points during the game. 

### Summary

From this survey of approaches as well as phenomena and theories, I think there are a few takeaways. I've highlighted some places where further work is needed to answer the question of how well do broad-coverage psycholinguistic approaches explain iterated reference game results. Some of this is completely outside the reference domain -- we could do with a better understanding of (general) language planning and production, and we could benefit from natural language processing models that did compositionality that could be plugged into Bayesian frameworks to interface with real data. There are also some computational and modeling directions, highlighted above. 

One other direction is better characterizing the explanandum: what exactly are the phenomena we are hoping to characterize? While there have been many studies of iterated reference games across some variety of conditions, some theoretically relevant aspects of the space are underexplored. Some of the reference game specific theories focus on narrow parts of iterated reference game space, while all the broad coverage approaches don't posit "special" cases. Rather, they all expect a mostly continuous relationship between circumstantial knobs and the outcome measures. From a modeling perspective, having more data and a wider range of data also reduces some concerns that we are overfitting to a very narrow circumstance. 

Thus, I believe one necessity to substantial progress in the reference game domain is a better empirical and descriptive understanding of the phenomena of interest. How do circumstantial knobs (group size, communication modality, stimuli, etc.) push around the extend to which we observe reduction, convention formation, and partner specificity? We don't have to finely map the entire landscape, but some sense of the geography of experimental space is necessary [@almaatouq2024]. 

Another question that some more variable experimental circumstances may answer is of these phenomena of interest, how closely related are they? At least where it's been studied, reduction, semantic alignment within a group, and partner specificity have patterned together (to the point where some metrics are used as proxies for each other). How closely are they actually linked? Does reduction only occur via convention formation? A greater range of experimental situations could tell how well these separate versus correlate in different situations, which will in turn clarify what theory should explain. 


## Outline of the dissertation

In this dissertation, we expand the empirical foundation of iterated reference games in three directions, with the aim of addressing some theoretical assumptions and questions and providing some data for computational modeling in the future. We also apply some computational models to survey coarse-grained patterns of changes in semantic similarities.  

In Chapter 2, we address the generalization patterns of the key patterns of results in iterated reference games, by examining the trajectories of convention formation in games of varying small group sizes and varying communication channel capacities. This expands the empirical foundation to mimic more of the different circumstances in which communication occurs in the real world, and allows for a test of how entangled the different reduction phenomena really are. 

In Chapter 3, we turn to the developmental timeline of the communication and coordination skills embedded in iterated reference tasks. Here we re-visit historical claims that children are too egocentric to produce successful ad-hoc referential expressions, which is fairly incompatible with more recent work showing nascent pragmatic language use and communication skills in preschoolers. This different context again provides a test of how entangled different observed reduction phenomena really are and provides insights into how language use fits into broader cognitive and linguistic development. 

Finally, in Chapter 4, we measure the level of opacity in the referential expressions produced in iterated reference games (using the corpus of reference games from Chapter 2). Taking inspiration from lexical uncertainty models, we use both naive human matchers and computational proxies to determine how far from "baseline semantics" referential expressions are at different stages of convention formation. These patterns are a test of at least the strongest versions of efficiency and audience design claims and give us a better understanding of what sort of partner-specificity is at play. 

In the last chapter, I conclude with a discussion of where this leaves us and what directions seem most promising from here. 


%TODO FOR LATER FIX REFERENCES!!!

<!--
# Somewhere bin

 On the production side, @horton1996 attempted to test this theory by comparing utterances produced with and without time pressure. They interpret the apparently ego-centric utterances in the speeded condition as evidence that initial utterance planning is ego-centric, but that monitoring and fixing of the utterance may take into account the listener's perspective, and may occur prior to utterance initiation. 
 
In principle, the pragmatic communicative behavior of reference games is a key candidate for modelling with  RSA frameworks, but degrees of flexibility and the issue of scaling to open classes of descriptions and the corresponding need for flexible semantics may prove challenges.

% want some sort of iterated ref game are used for a variety of things since they work well
% has fairly well characterized common patterns, but there are questions around the edge cases
% also big theoretical questions about how to interpret the results -- touch here on the phenomena, and problematize  the verbal theories that go with them, and where the open questions are in terms of both the phenomena and whether a specific theory is needed or whether these are parts of larger effects. 

The communication and conversation literature, especially with regard to referring expressions, has provided useful descriptive characterizations of how people communicate in naturalistic and experimental settings. . These describe consistently observable trends, but the necessary and sufficient conditions and the dose-response relationships tend to lack specification. These theories provide a set of potential targets for computational models, although in many cases, more work to clarify the target phenomenon is needed.  

While intuitively an important distinction, it's not necessarily a well-formed one. Is this asking whether model-based or model-free approaches capture observed phenomena better? In the present with pretty cool AI systems, there's an issue that appearances and internal architecture don't always align. We can have black-box systems that seem to match rule governed behavior. 

A Bayesian inference approach could complicate this by asking whether shared-ness is important or whether this is really a way of saying something about your priors on the other person's knowledge or lexicon are above some threshold of thinking they probably will understand. The question then becomes how mutual this has to be or whether one can use similar mechanisms to when you believe they know something even if you don't (they know where the key is, even if you don't). 
* is the modeling of joint knowledge handled differently than other situations where you try to model another's knowledge to communicate? not clear that it should be, especially given the accomodation and assorted rules for getting CG -- maybe we should drop the determinism and accept that it's all more probabilistic? 

How do we determine that something is mutually known with another person?  Enumerating all the options doesn't work because we don't always have certainty around what is or isn't mutually known; someone can look at something in shared visual presence, but not know about it because they weren't attending. Visual presence may be a good heuristic, but good heuristics won't be perfect, and humans operate under uncertainty. Understanding human communicative behavior also doesn't require a deterministic answer to when something is mutually known: what another person knows or can be expected to understand is something that computational models will want as an input or intermediary, so that it can be used to evaluate utterance options. However, the knowledge state can clearly be probabilistic and may be inferred from empirical data. Bayesian approaches are great at uncertainty! 


%TODO FOR LATER Gabe Doyle stuff

%TODO FOR LATER connect to the lexical side 

aim high and low is a useful system if the knowledge states are neatly nested, but breaks down if the listener knowledge states are more complementary. this may be also be dependent on goals and how important it is for everyone to get it right versus for some people to get it right. backchannel options might also matter. 
Heirarchical Bayesian models or noisy models could account for gradients if tracking mutliple people leads to fuzziness, it could be possible to place inference limitations to get a noisy version of the full system rather than require either full inference or heuristics. (lol maybe cite Ben's cogsci) 

From an efficiency perspective, effort sharing based on relative abilities and load makes a lot of sense. The (efficient) alignment between production and comprehension abilities is also clearly wrapped up in here, even if it mostly just makes study this all harder. 

possibly discuss if this is an efficiency side production thing, or something accounted for in Bayesian pragmatics to align to the listeners inferred priors or ... 

- Information Bottleneck -- complexity of language is MI between words and cognitive meaning representations
    

- feels like there’s some tension between info theory’s representation invariance and like codeability ? I guess it’s mismatch between the distribution lang is optim for and the distribuiton you have?

in general, we have much better models for the processing side (surprisal) than the production side of course

and then unclear how \*task comprehension\* relates to these things as well

seems like there’s how do we get language & how do we get language **usage** and they definitely relate

The CHAI framework seems promising in that it qualitatively produces some of the patterns that have been most difficult to explain, namely why it would make sense to change descriptions when nothing in the context has changed. CHAI identifies that something in the context has changed -- the conversation history has evolved and changed the word-meaning pairings in the speaker and listener lexica. This solves the issue of presenting a plausible and somewhat testable theory. It leaves open a lot of implementation questions about how to scale it up to be able to interact with (non-simulated, open vocabulary) data, and the model is likely to have a fair number of free parameters so it's unclear how to test it stringently. 

    
While much of this is coming from higher more computational level stuff, the actual production and comprehension of utterances in communication (and in reference games in particular) has to go through language processing, which may impose its own bottlenecks and constraints. These could potential serve as reasons for bounding things in an "approximately rational" model. 

%TODO  FOR LATER maybe cite the new shain paper as an example of how different levels influence each other 


As these experiments show, it's empirically difficult to do so when the measurements are far from the constructs and there are many nuisance variables to abstract over. An experiment compares two conditions with different objects visible to the speaker but not the listener (or vice versa), and can claim that for this set up and these objects, people look at the privileged object some amount. Is looking at the object predicted only by ego-centrism theory or can it also be predicted by some other pattern such as the constraint based approach? When a different experiment with different stimuli has a different result, is this because of nuisance differences in the stimuli? Or because of critical differences in how well each stimuli matched the verbal description? Even if we had well-characterized descriptive work about when this early-reaction occurs in terms of stimuli and conditions, there's still an interpretive question of what the early looks mean. 

Some of the experiments around egocentrism try adding time pressure to get at earlier stages of production, but we don't actually know how time pressure interacts with the production system -- does time pressure cause people to short-cut off the end, or to satisfice more at all the stages? 

The communication and reference game literature provides descriptive theories that identify some phenomena of interest and raises questions around whether these phenomena occur intentionally or emerge as a by-product of other processes. Within the narrow range of experimental paradigms, clear patterns around reduction, convention, and partner-specificity are robustly observed, and could form a list of results that models could hope to explain and predict. Our current understanding of these phenomena is limited. We do not have ways to predict them quantitatively, nor do we have a grasp on the necessary or sufficient experimental conditions under which they occur (to what extent). In many cases, we do not even have consensus on how exactly the characterize the phenomena. In order to build strong theories, we first need clarity around what exactly the theories should be accounting for. A core theoretical question is whether the observed patterns of reduction, convention, and partner-specificity require "special" mechanisms, or whether these results can sufficiently be explained by broader coverage theories of efficiency and rational communication. 

%could probably make this less snarky? 



One question that comes up is how "special" are the target phenomena? How purely linguistic? Does it require children? Are there any aspects of the communication that make qualitiative differences (group size, back channel?) 

Want a better map of the empirical landscape, so we know what exactly to try to model. Also, good theories rely on a combination of the right coverage of data, the right computational links/measurements, and the right formalism. The tools for computational links are definitely getting a lot better recently, enabling some analyses to scale and making other analyses possible. However, there is still some gap between matching up computational models to the data. 


One feature we may want in models is parameters (or other built in option spaces) that can be tuned to represent differences in games such as number of participants or age of participants or the number of stimuli or their codability or other game features. There is an empirical question whether any of these dimensions (and if so which) produce qualitatively totally different results, like a catastrophic failure that needs a different models to account for. Otherwise, we'd want models that could take different inputs and predict quantitatively different outcomes. The more situation -- outcome data we have the more we could hope to constrain model free-parameters.

One of the really cool things about language is its extensibility. The combinatorial feature of this is well noted -- we can produce and comprehend sentences that we have never produced or heard before, even ones that perhaps no one has produced or heard before. Beyond the compositionality portion, we can also stretch the meanings of words and constructions to match communicative needs. That's one of the ways language evolves, as new words and constructions come to be to accomodate new scientific and cultural developments that need referring to. However, this also plays out at a finer grained scale -- many neologisms or creative usages do not become fixed in langauge as a whole but are fleeting -- useful in the moment to serve a communicative need, or perhaps sticking around as a joke between small groups. 
-->
